name: Self Compare
on: [push]
jobs:
  self_compare:
    name: Self Compare
    runs-on: Ubuntu-latest
    steps:
    - uses: action/checkout@v4
    - name: Run a script
      run: diff file.txt file.txt
